### ISSUE TITLE
Published fork to VSIX Gallery

### ISSUE THREAD

**Issue by Christopher-St** [madskristensen/CommandTableInfo#4]
I published [my fork](https://github.com/Christopher-St/CommandTableInfo/) to [Open VSIX Gallery](http://vsixgallery.com/extension/1a973c52-a674-48d8-a276-65ddab1ac598/) when I built on AppVeyor. It looks to have replaced the real one in the feed. Seems like a security risk, but I'm not sure who those builds are intended for.  

Apologies, took me by surprise! Thanks for the great extension tools!

**Comment by madskristensen** [comment]
Yeah, the vsix gallery is brittle. Just change the ID to a new guid in the .vsixmanifest
